package main

//go:generate go run github.com/cilium/ebpf/cmd/bpf2go -cc clang bpf execve.c -- -I../headers
// This directive runs the `bpf2go` tool to generate Go bindings for the eBPF program defined in `execve.c`.
// It uses the Clang compiler (`-cc clang`) and includes the headers from `../headers`.

import (
	"C" // Enables calling C functions from the Go program.
	"fmt"

	"github.com/cilium/ebpf/link" // Provides tools to attach eBPF programs to kernel hooks.
)

func main() {
	// Define a variable to hold the eBPF objects generated by bpf2go.
	ebpfObj := bpfObjects{}

	// Load the eBPF program into the kernel using the generated bindings.
	err := loadBpfObjects(&ebpfObj, nil)
	if err != nil {
		// If loading fails, terminate the program with an error message.
		panic(err)
	}
	// Ensure the eBPF objects are closed properly to release resources.
	defer ebpfObj.Close()

	// Attach the eBPF program to the sys_enter_execve tracepoint.
	hookExecve, err := link.Tracepoint("syscalls", "sys_enter_execve", ebpfObj.TraceExecve, nil)
	if err != nil {
		panic(err)
	}
	defer hookExecve.Close()

	// Attach the eBPF program to the sys_enter_fork tracepoint.
	hookFork, err := link.Tracepoint("syscalls", "sys_enter_fork", ebpfObj.TraceFork, nil)
	if err != nil {
		panic(err)
	}
	defer hookFork.Close()

	// Attach the eBPF program to the sys_enter_clone tracepoint.
	hookClone, err := link.Tracepoint("syscalls", "sys_enter_clone", ebpfObj.TraceClone, nil)
	if err != nil {
		panic(err)
	}
	defer hookClone.Close()

	// Attach the eBPF program to the sys_enter_openat tracepoint.
	hookOpenat, err := link.Tracepoint("syscalls", "sys_enter_openat", ebpfObj.TraceOpenat, nil)
	if err != nil {
		panic(err)
	}
	defer hookOpenat.Close()

	// Attach the eBPF program to the sys_enter_read tracepoint.
	// hookRead, err := link.Tracepoint("syscalls", "sys_enter_read", ebpfObj.TraceRead, nil)
	// if err != nil {
	// 	panic(err)
	// }
	// defer hookRead.Close()

	// Print a message to indicate that the program is waiting for events.
	fmt.Println("Waiting for events to trigger!")
	select {}
}
